disabled_rules:
- trailing_whitespace
- vertical_whitespace
- colon
- type_name
- switch_case_alignment
- trailing_newline
- todo


opt_in_rules:
- empty_count
- empty_string


excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

identifier_name:
  allowed_symbols: "_"
  min_length: 2
  max_length: 
    warning: 90
    error: 1000
  excluded:
    - id
    - r
    - g
    - b
    - a
    - f
    - to
    - i
    - j
    - x
    - y
    - z


line_length:
    warning: 300
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true

function_body_length:
    warning: 300
    error: 500

function_parameter_count:
    warning: 6
    error: 8

type_body_length:
    warning: 300
    error: 500

file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true

cyclomatic_complexity:
    warning: 15
    error: 25

large_tuple:
    warning: 4
    error: 5

reporter: "xcode"

